---
- name: Download packages
  shell: wget -O /tmp/{{ item | basename }} {{ item }}
  loop: "{{ elk_packages }}"

- name: Install packages
  shell: dpkg -i /tmp/*.deb
  args:
    chdir: /tmp
  register: dpkg_result
  ignore_errors: yes

- name: Fix dependencies
  apt:
    name: -f
    state: present
  when: dpkg_result.rc != 0

- name: Clear after work
  shell: rm -rf /tmp/*.deb

- name: Configure Elasticsearch
  block:
    - name: Template config
      template:
        src: templates/elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml
        mode: '0644'

    - name: Start ElasticSearch
      systemd:
        name: elasticsearch
        enabled: yes
        state: started
  when: elastic in elk_packages

- name: Configure Logstash
  block:
    - name: Template config
      template:
        src: templates/logstash.yml.j2
        dest: /etc/logstash/logstash.yml
        mode: '0644'

    - name: Start Logstash
      systemd:
        name: logstash
        enabled: yes
        state: started
  when: logstash in elk_packages

- name: Configure Kibana
  block:
    - name: Template config
      template:
        src: templates/kibana.yml.j2
        dest: /etc/kibana/kibana.yml
        mode: '0644'

    - name: Start Kibana
      systemd:
        name: kibana
        enabled: yes
        state: started
  when: kibana in elk_packages

- name: Configure FileBeat
  block:
    - name: Template config
      template:
        src: templates/filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
        mode: '0644'

    - name: Start FileBeat
      systemd:
        name: filebeat
        enabled: yes
        state: started
  when: filebeat in elk_packages
