---
- name: Elasticsearch
  block:

    - name: Check elastic package exist
      shell: dpkg -l | grep elastic
      register: elastic_check
      ignore_errors: yes

    - name: Install missing package
      block:
        - name: Download packages
          shell: wget -O /tmp/{{ elastic | basename }} {{ elastic }}

        - name: Install packages
          shell: dpkg -i /tmp/{{ elastic | basename }}

        - name: Clear after install
          shell: rm -rf /tmp/{{ elastic | basename }}
      when: elastic_check.rc != 0

    - name: Template config
      template:
        src: templates/elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml
        mode: '0664'

    - name: Template jvm options
      template:
        src: templates/jvm.options.j2
        dest: /etc/elasticsearch/jvm.options
        mode: '0664'

    - name: Start ElasticSearch
      systemd:
        name: elasticsearch
        enabled: yes
        state: restarted
  when: elastic in elk_packages

- name: Logstash
  block:

    - name: Check logstash package exist
      shell: dpkg -l | grep logstash
      register: logstash_check
      ignore_errors: yes

    - name: Install missing package
      block:
        - name: Download packages
          shell: wget -O /tmp/{{ logstash | basename }} {{ logstash }}

        - name: Install packages
          shell: dpkg -i /tmp/{{ logstash | basename }}

        - name: Clear after install
          shell: rm -rf /tmp/{{ logstash | basename }}
      when: logstash_check.rc != 0

    - name: Template config
      template:
        src: templates/logstash.yml.j2
        dest: /etc/logstash/logstash.yml
        mode: '0664'

    - name: Template config
      template:
        src: templates/logstash.conf.j2
        dest: /etc/logstash/conf.d/logstash.conf
        mode: '0664'

    - name: Start Logstash
      systemd:
        name: logstash
        enabled: yes
        state: restarted
  when: logstash in elk_packages

- name: Kibana
  block:

    - name: Check kibana package exist
      shell: dpkg -l | grep kibana
      register: kibana_check
      ignore_errors: yes

    - name: Install missing package
      block:
        - name: Download packages
          shell: wget -O /tmp/{{ kibana | basename }} {{ kibana }}

        - name: Install packages
          shell: dpkg -i /tmp/{{ kibana | basename }}

        - name: Clear after install
          shell: rm -rf /tmp/{{ kibana | basename }}
      when: kibana_check.rc != 0

    - name: Template config
      template:
        src: templates/kibana.yml.j2
        dest: /etc/kibana/kibana.yml
        mode: '0664'

    - name: Start Kibana
      systemd:
        name: kibana
        enabled: yes
        state: restarted
  when: kibana in elk_packages

- name: FileBeat
  block:

    - name: Check filebeat package exist
      shell: dpkg -l | grep filebeat
      register: filebeat_check
      ignore_errors: yes

    - name: Install missing package
      block:
        - name: Download packages
          shell: wget -O /tmp/{{ filebeat | basename }} {{ filebeat }}

        - name: Install packages
          shell: dpkg -i /tmp/{{ filebeat | basename }}

        - name: Clear after install
          shell: rm -rf /tmp/{{ filebeat | basename }}
      when: filebeat_check.rc != 0

    - name: Template config
      template:
        src: templates/filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
        mode: '0644'

    - name: Start FileBeat
      systemd:
        name: filebeat
        enabled: yes
        state: restarted
  when: filebeat in elk_packages
