---
- name: Elasticsearch
  block:
    - name: Install missing package
      apt:
        name: elasticsearch
        state: present

    - name: Template config
      template:
        src: templates/elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml
        mode: '0664'

    - name: Template jvm options
      template:
        src: templates/jvm.options.j2
        dest: /etc/elasticsearch/jvm.options
        mode: '0664'

    - name: Start ElasticSearch
      systemd:
        name: elasticsearch
        enabled: yes
        state: restarted
  when: '"elastic" in elk_packages'

- name: Logstash
  block:
    - name: Install missing package
      apt:
        name: logstash
        state: present

    - name: Template config
      template:
        src: templates/logstash.yml.j2
        dest: /etc/logstash/logstash.yml
        mode: '0664'

    - name: Template config
      template:
        src: templates/logstash.conf.j2
        dest: /etc/logstash/conf.d/logstash.conf
        mode: '0664'

    - name: Start Logstash
      systemd:
        name: logstash
        enabled: yes
        state: restarted
  when: '"logstash" in elk_packages'

- name: Kibana
  block:
    - name: Install missing package
      apt:
        name: kibana
        state: present

    - name: Template config
      template:
        src: templates/kibana.yml.j2
        dest: /etc/kibana/kibana.yml
        mode: '0664'

    - name: Start Kibana
      systemd:
        name: kibana
        enabled: yes
        state: restarted
  when: '"kibana" in elk_packages'

- name: FileBeat
  block:
    - name: Install missing package
      apt:
        name: filebeat
        state: present

    - name: Template config
      template:
        src: templates/filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
        mode: '0644'

    - name: Start FileBeat
      systemd:
        name: filebeat
        enabled: yes
        state: restarted
  when: '"filebeat" in elk_packages'

- name: MetricBeat
  block:
    - name: Install missing package
      apt:
        name: metricbeat
        state: present

    - name: Template config
      template:
        src: templates/metricbeat.yml.j2
        dest: /etc/metricbeat/metricbeat.yml
        mode: '0644'

    - name: Collect packages info
      shell: "dpkg -l | awk '{print $2}' | grep -v '^$'"
      register: packages

    - name: Activate modules
      shell: "metricbeat modules enable {{ item }}"
      loop: "{{ metricbeat_modules }}"
      when: (item == 'linux') or
            (item == 'nginx' and 'nginx' in packages|lower) or
            (item == 'elasticsearch-xpack' and 'elasticsearch' in packages|lower) or
            (item == 'logstash-xpack' and 'logstash' in packages|lower) or
            (item == 'kibana-xpack' and 'kibana' in packages|lower)

    - name: Start MetricBeat
      systemd:
        name: metricbeat
        enabled: yes
        state: restarted
  when: '"metricbeat" in elk_packages'
