---
- name: OpenSearch
  block:
    - name: Install OpenSearch
      apt:
        name: opensearch
        state: present
      environment:
        OPENSEARCH_INITIAL_ADMIN_PASSWORD: "{{ opensearch_admin_password }}"

    - name: Template config
      template:
        src: templates/opensearch.yml.j2
        dest: "{{ ops_conf }}/opensearch.yml"
        mode: '0664'

    - name: Start OpenSearch
      systemd:
        name: opensearch
        enabled: yes
        state: restarted
  when: '"opensearch" in ops_packages'

- name: Dashboard
  block:
    - name: Install Dashboard 
      apt:
        name: opensearch-dashboards
        state: present

    - name: Template config
      template:
        src: templates/opensearch_dashboards.yml.j2
        dest: "{{ dash_conf }}/opensearch_dashboards.yml"
        mode: '0664'

    - name: Start Dashboard
      systemd:
        name: opensearch-dashboards
        enabled: yes
        state: restarted
  when: '"dashboard" in ops_packages'
