---
- hosts: all
  become: yes
  roles:
    - PrepareNewOS

- hosts: 
    - enode1
    - enode2
    - enode3
  become: yes
  vars:
    elk_packages:
      - "{{ elastic }}"
      - "{{ filebeat }}"
    cluster_hosts: "enode1, enode2, enode3"
  roles:
    - ElasticStack

- hosts: lnode
  become: yes
  vars:
    elk_packages:
      - "{{ logstash }}"
      - "{{ filebeat }}"
  roles:
    - ElasticStack

- hosts: knode
  become: yes
  vars:
    elk_packages:
      - "{{ kibana }}"
      - "{{ filebeat }}"
    cluster_hosts: "http://enode1:9200, http://enode2:9200, http://enode3:9200"
  roles:
    - ElasticStack

- hosts: local-repo
  become: yes
  vars:
    files:
      - "{{ elastic }}"
      - "{{ logstash }}"
      - "{{ kibana }}"
      - "{{ filebeat }}"
    elk_packages:
      - "{{ filebeat }}"
  roles:
    - Repository
    - ElasticStack
