---
- hosts: local-repo
  become: yes
  vars:
    files:
    # - "{{ elastic }}"
    # - "{{ logstash }}"
    # - "{{ kibana }}"
    # - "{{ filebeat }}"
    # - "{{ metricbeat }}"
    - "{{ opensearch }}"
    - "{{ ops_dashboard }}"
    - "{{ fluentbit }}"
  roles:
    - Repository

- hosts: all
  become: yes
  roles:
    - PrepareNewOS

### OpenSearch
- hosts: onode1, onode2, onode3
  become: yes
  vars:
    ops_packages:
      - opensearch
  roles:
    - OpenSearchStack

- hosts: dnode
  become: yes
  vars:
    ops_packages:
      - dashboard
  roles:
    - OpenSearchStack

- hosts: onode1, onode2, onode3, dnode
  become: yes
  vars:
    ops_packages:
      - fluentbit
  roles:
    - OpenSearchStack

### ElasticSearch
- hosts: enode1, enode2, enode3
  become: yes
  vars:
    elk_packages:
      - elastic
  roles:
    - ElasticStack

- hosts: lnode
  become: yes
  vars:
    elk_packages:
      - logstash
  roles:
    - ElasticStack

- hosts: knode
  become: yes
  vars:
    elk_packages:
      - kibana
  roles:
    - ElasticStack

- hosts: enode1, enode2, enode3, lnode, knode
  become: yes
  vars:
    elk_packages:
      - filebeat
      - metricbeat
  roles:
    - ElasticStack
