---
- hosts: local-repo
  become: yes
  roles:
    - Repository

- hosts: all
  become: yes
  vars:
    elk_packages:
      - filebeat
      - metricbeat
  roles:
    - PrepareNewOS
    - ElasticStack

- hosts: enode1, enode2, enode3
  become: yes
  vars:
    elk_packages:
      - elastic
  roles:
    - ElasticStack

- hosts: lnode
  become: yes
  vars:
    elk_packages:
      - logstash
  roles:
    - ElasticStack

- hosts: knode
  become: yes
  vars:
    elk_packages:
      - kibana
  roles:
    - ElasticStack
