---
- hosts: all
  become: yes
  roles:
    - PrepareNewOS

- hosts: elk-master
  become: yes
  vars:
    elk_ver: 8.10.3
    elk_packages:
      - "{{ elastic }}"
      - "{{ kibana }}"
      - "{{ logstash }}"
  roles:
    - ElasticStack