---
- hosts: all
  become: yes
  roles:
    - PrepareNewOS

- hosts: 
    - enode1
    - enode2
    - enode3
  become: yes
  vars:
    elk_packages:
      - "{{ elastic }}"
      - "{{ filebeat }}"
  roles:
    - ElasticStack

- hosts: lnode
  become: yes
  vars:
    elk_packages:
      - "{{ logstash }}"
      - "{{ filebeat }}"
  roles:
    - ElasticStack

- hosts: knode
  become: yes
  vars:
    elk_packages:
      - "{{ kibana }}"
      - "{{ filebeat }}"
  roles:
    - ElasticStack
