---
- name: Install Nginx web server
  apt:
    name: nginx
    state: present

- name: Template Nginx configuration
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0664'

- name: Create nginx user
  user:
    name: nginx
    state: present
    system: yes

- name: Ensure the repository folder exists
  file:
    path: "{{ default_repo_folder }}"
    state: directory
    mode: '0755'

- name: Check if files exist in the repository
  stat:
    path: "{{ default_repo_folder }}/{{ item | basename }}"
  register: file_stats
  with_items: "{{ files }}"

- name: Download files if they do not exist
  get_url:
    url: "{{ item.item }}"
    dest: "{{ default_repo_folder }}/{{ item.item | basename }}"
  when: not item.stat.exists
  with_items: "{{ file_stats.results }}"

- name: Install dev packages for create repository
  apt:
    name: "{{ dpkg_packages }}"
    state: present

- name: Clear Packages file
  file:
    state: absent
    path: "{{ default_repo_folder }}/Packages.gz"

- name: Create Packages file
  shell: "dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz"
  args:
    chdir: "{{ default_repo_folder }}"

- name: Start Nginx
  systemd:
    name: nginx
    enabled: yes
    state: restarted
