---
#### Nginx
default_repo_folder: /var/www/html/repo

#### Elastic
elk_ver: 8.10.3
yandex: "mirror.yandex.ru/mirrors/elastic/8/pool/main"
elastic: "https://{{ yandex }}/e/elasticsearch/elasticsearch-{{ elk_ver }}-amd64.deb"
logstash: "https://{{ yandex }}/l/logstash/logstash-{{ elk_ver }}-amd64.deb"
kibana: "https://{{ yandex }}/k/kibana/kibana-{{ elk_ver }}-amd64.deb"
filebeat: "https://{{ yandex }}/f/filebeat/filebeat-{{ elk_ver }}-amd64.deb"
metricbeat: "https://{{ yandex }}/m/metricbeat/metricbeat-{{ elk_ver }}-amd64.deb"

#### OpenSearch
ops_ver: 2.17.1
opensearch: "https://artifacts.opensearch.org/releases/bundle/opensearch/{{ ops_ver }}/opensearch-{{ ops_ver }}-linux-x64.deb"
ops_dashboard: "https://artifacts.opensearch.org/releases/bundle/opensearch-dashboards/{{ ops_ver }}/opensearch-dashboards-{{ ops_ver }}-linux-x64.deb"
fluentbit: "https://packages.fluentbit.io/debian/bookworm/fluent-bit_3.1.9_amd64.deb"

#### Repository
dpkg_packages:
  - dpkg-dev
  - debhelper
  - build-essential
